POST http://localhost:8080/api/payments
Accept: application/json
Content-Type: application/json

{
  "requestId": 1,
  "value": "200 PLN"
}

###

GET http://localhost:8080/api/payments/48907f10-f309-4865-84eb-8c8e03325dac
Accept: application/json
Content-Type: application/json

###

GET http://localhost:8080/api/payments/confirmed
Accept: application/json
Content-Type: application/json

###

// @no-cookie-jar
POST http://localhost:8100/auth/realms/cloud/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=cloud-service&username=jan&password=123&grant_type=password

> {%client.global.set("auth_token", response.body.access_token);%}

###

// @no-cookie-jar
POST http://localhost:8100/auth/realms/cloud/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=cloud-service&grant_type=refresh_token&refresh_token=eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJlMDNhY2U2Mi00MTQ5LTQwMzItODViYy01YjEzMjg1OTJlYTAifQ.eyJleHAiOjE2NDg4MDkwNDIsImlhdCI6MTY0ODgwNzI0MiwianRpIjoiNDZmNGNlZjctZjkyNi00MGE3LTkxMDUtODMxODM0NjE0YWI1IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MTAwL2F1dGgvcmVhbG1zL2Nsb3VkIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo4MTAwL2F1dGgvcmVhbG1zL2Nsb3VkIiwic3ViIjoiZThjOGQ5YWQtNWYyMy00MzNkLWE1MTItMjEzZTU2NTE1ZTZiIiwidHlwIjoiUmVmcmVzaCIsImF6cCI6ImNsb3VkLXNlcnZpY2UiLCJzZXNzaW9uX3N0YXRlIjoiN2NmYjc3NDMtYjg5MC00ODFiLTliZjgtYzJkZTNmMTRkN2JhIiwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwic2lkIjoiN2NmYjc3NDMtYjg5MC00ODFiLTliZjgtYzJkZTNmMTRkN2JhIn0.TSY9cZgoeiILeGulJTJYBBl_6biB99dEl0gFmJUoDCQ
