version: '3'
services:
  database:
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=shop
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGDATA=/var/lib/postgresql/data/application
    volumes:
      - ./data:/var/lib/postgresql/data/application
  pgadmin:
    image: dpage/pgadmin4:6.2
    ports:
      - "8000:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=training@sages.pl
      - PGADMIN_DEFAULT_PASSWORD=admin
